In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu117


In [2]:
scalar = torch.tensor(49)
scalar

tensor(49)

In [3]:
scalar.ndim

0

In [4]:
# accessing the value of a scalar in pytorch
scalar.item()

49

In [5]:
vector = torch.tensor([1,2,3,4])
vector

tensor([1, 2, 3, 4])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([4])

In [8]:
MATRIX = torch.tensor([[1,2,3],[4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.size()

torch.Size([2, 3])

In [11]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 4, 3])

In [14]:
### RANDOM TENSORS

In [15]:
random_tensor = torch.rand(size = (3,4,5))

In [16]:
random_tensor, random_tensor.dtype

(tensor([[[0.4902, 0.6007, 0.0348, 0.0863, 0.5147],
          [0.0255, 0.7154, 0.9652, 0.8278, 0.2648],
          [0.1811, 0.3039, 0.3810, 0.9292, 0.4756],
          [0.5112, 0.3625, 0.6421, 0.7303, 0.4208]],
 
         [[0.0206, 0.5981, 0.2928, 0.7995, 0.9900],
          [0.4383, 0.4532, 0.5330, 0.1821, 0.2096],
          [0.9899, 0.4661, 0.8580, 0.9229, 0.4752],
          [0.0610, 0.1687, 0.0904, 0.6936, 0.6450]],
 
         [[0.4435, 0.5737, 0.5684, 0.1581, 0.2800],
          [0.7238, 0.1056, 0.2359, 0.4399, 0.5241],
          [0.9550, 0.0292, 0.4553, 0.6453, 0.4493],
          [0.7387, 0.7523, 0.2562, 0.7847, 0.5740]]]),
 torch.float32)

In [17]:
random_image_size_tensor = torch.rand(size=(224,224,3))

In [18]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
### Zero and One Tensors

In [20]:
zeros = torch.zeros(size=(2,3))
zeros, zeros.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32)

In [21]:
ones = torch.ones(size=(2,3))
ones, ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

In [22]:
### Range in tensors

In [23]:
to_ten = torch.arange(0,10,1)

In [24]:
to_ten, to_ten.dtype, to_ten.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64, torch.Size([10]))

In [25]:
### zero tensors like another tensor

In [26]:
ten_zeros = torch.zeros_like(input=to_ten)
ten_zeros, ten_zeros.shape, ten_zeros.dtype

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.Size([10]), torch.int64)

In [27]:
ten_zeros.device

device(type='cpu')

In [28]:
### Tensor Operations

In [29]:
# ADDITION, MULTIPLICATION, SUBTRACTION, DIVISION

In [30]:
# addition of a scalar to a tensor
vector + 10

tensor([11, 12, 13, 14])

In [31]:
# * for element-wise multiplication
vector * 10

tensor([10, 20, 30, 40])

In [32]:
# torch.matmul is significantly faster than looping
# torch.matmul for matrix multiplication
torch.matmul(vector,vector)

tensor(30)

In [33]:
#Transpose of a matrix/tensor

In [34]:
tensor_A = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor_B = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor_A, tensor_B

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

In [35]:
# transpose of tensor_A
tensor_A.T

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [36]:
torch.transpose(tensor_B, 0, 2)

tensor([[[1],
         [4],
         [7]],

        [[2],
         [5],
         [8]],

        [[3],
         [6],
         [9]]])

In [37]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)

x = torch.tensor([[1,2],[3,4],[5,6]], dtype=torch.float32)

output = linear(x)
print(f"Input shape: {x.shape}")
print(f"Output:\n{output}\nOutput Shape: {output.shape}")

Input shape: torch.Size([3, 2])
Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)
Output Shape: torch.Size([3, 6])


In [38]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")
print(f"Max index: {x.argmax()}")
print(f"Min index: {x.argmin()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450
Max index: 9
Min index: 0


In [40]:
print(x.dtype)

torch.int64


In [41]:
x.type(torch.float32)

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [42]:
x.dtype

torch.int64

In [44]:
"""
Reshaping, stacking, squeezing and unsqueezing
"""

'\nReshaping, stacking, squeezing and unsqueezing\n'

In [45]:
x = torch.arange(1, 10, 1)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [58]:
# view the changes before applying
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [61]:
# changing the view of the tensor also changes the original tensor
z[:, 1] = 0
z, x

(tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0]]), tensor([0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [64]:
# stacking tensors
x_stacked = torch.stack([x,x,x], dim=0)
x_stacked

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [65]:
# torch.permute to change the dimensions

In [67]:
x_origin = torch.rand(size=(224,224,3))

x_permuted = x_origin.permute(2,0,1)

x_origin.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [69]:
# selecting data from tensors
x = torch.arange(1, 28).reshape(3, 3, 3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]],
 
         [[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]]]),
 torch.Size([3, 3, 3]))

In [73]:
 x[0], x[1], x[2]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]),
 tensor([[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]))

In [80]:
# regular array indexing
x[0][0]

tensor([1, 2, 3])

In [81]:
# similar to numpy array indexing
x[:, 0, :]

tensor([[ 1,  2,  3],
        [10, 11, 12],
        [19, 20, 21]])

In [82]:
# indexing to return 3,6,9
x[0, :, 2]

tensor([3, 6, 9])

In [83]:
# pytorch tensors and numpy: torch.from_numpy(ndarray)
# torch.Tensor.numpy()

In [101]:
# numpy uses float64 as default
array = np.arange(1.0, 10.0, dtype = np.float32)
tensor = torch.from_numpy(array)

In [102]:
tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [108]:
# from_numpy(ndarray) creates a separate memory map
array = array+1

In [109]:
tensor, array

(tensor([ 5.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.], dtype=float32))

In [110]:
tensor[0] = 5
tensor, array

(tensor([ 5.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.], dtype=float32))

In [112]:
# tensor to numpy
tensor = torch.arange(1.0, 10.0)
tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [114]:
np_arr = torch.Tensor.numpy(tensor)
np_arr

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [117]:
# change the tensor: creates a different memory map
tensor = tensor + 1
tensor, np_arr

(tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32))

In [131]:
# reproducibility
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
x = torch.rand(3, 3)
y = torch.rand(3, 3)

x, y

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[0.1332, 0.9346, 0.5936],
         [0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739]]))

In [133]:
## Running tensors and pytorch objects on GPUs

In [134]:
## Getting a GPU
## use google colab for a free version
## use cloud computing using GCP, AWS, Azure, etc

In [135]:
!nvidia-smi

Fri Nov 18 17:47:55 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   48C    P8     8W /  N/A |    388MiB /  6144MiB |     13%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [136]:
torch.cuda.is_available()

True

In [137]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [138]:
# Count the number of devices
torch.cuda.device_count()

1

In [139]:
# putting tensors on the gpu

tensor = torch.tensor([1,2,3], device="cpu")

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [141]:
tensor_gpu = torch.tensor([1,2,3], device=device)
tensor_gpu, tensor_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [143]:
# numpy does not work with gpu
tensor_gpu.cpu()

tensor([1, 2, 3])

In [144]:
### Exercises for pytorch fundamentals

In [168]:
t1 = torch.rand(size=(7,7))
t1

tensor([[0.3911, 0.3976, 0.2916, 0.8447, 0.7453, 0.6602, 0.2190],
        [0.0941, 0.5541, 0.6481, 0.2691, 0.3601, 0.8377, 0.5398],
        [0.5226, 0.3769, 0.0472, 0.0299, 0.2610, 0.2458, 0.6558],
        [0.3544, 0.3044, 0.9767, 0.6742, 0.8565, 0.2579, 0.2958],
        [0.6838, 0.1669, 0.1731, 0.4759, 0.3171, 0.1252, 0.7966],
        [0.9021, 0.5811, 0.4129, 0.0369, 0.3179, 0.6273, 0.7358],
        [0.4368, 0.3023, 0.7786, 0.1018, 0.8160, 0.3060, 0.5077]])

In [169]:
t2 = torch.rand(size=(1, 7))
t2

tensor([[0.4012, 0.5606, 0.3489, 0.8636, 0.4870, 0.8903, 0.9807]])

In [172]:
torch.matmul(t1, t2.T)

tensor([[2.3765],
        [2.2575],
        [1.4524],
        [2.1726],
        [1.8863],
        [2.2985],
        [1.8720]])

In [184]:
RAND_SEED = 0
torch.manual_seed(RAND_SEED)
t3 = torch.rand(size=(7, 7))
t4 = torch.rand(size=(1, 7))

In [185]:
t5 = torch.matmul(t3, t4.T)
t5, t5.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [186]:
torch.cuda.seed()

In [189]:
torch.manual_seed(RAND_SEED)
if torch.cuda.is_available():
    gpu1 = torch.rand(size=(2,3)).cuda()
    gpu2 = torch.rand(size=(2,3)).cuda()
gpu1, gpu2

(tensor([[0.4963, 0.7682, 0.0885],
         [0.1320, 0.3074, 0.6341]], device='cuda:0'),
 tensor([[0.4901, 0.8964, 0.4556],
         [0.6323, 0.3489, 0.4017]], device='cuda:0'))

In [192]:
out = torch.matmul(gpu1, gpu2.T)
out

tensor([[0.9722, 0.6174],
        [0.6292, 0.4455]], device='cuda:0')

In [193]:
torch.max(out)

tensor(0.9722, device='cuda:0')

In [194]:
torch.min(out)

tensor(0.4455, device='cuda:0')

In [195]:
torch.argmax(out)

tensor(0, device='cuda:0')

In [196]:
torch.argmin(out)

tensor(3, device='cuda:0')

In [201]:
torch.manual_seed(7)
rand_tens =  torch.rand(size=(1,1,1,10))
new_tens = torch.squeeze(rand_tens)
rand_tens, rand_tens.size(), new_tens, new_tens.size()

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))