In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu117


In [10]:
scalar = torch.tensor(49)
scalar

tensor(49)

In [11]:
scalar.ndim

0

In [13]:
# accessing the value of a scalar in pytorch
scalar.item()

49

In [14]:
vector = torch.tensor([1,2,3,4])
vector

tensor([1, 2, 3, 4])

In [15]:
vector.ndim

1

In [19]:
vector.shape

torch.Size([4])

In [21]:
MATRIX = torch.tensor([[1,2,3],[4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
MATRIX.ndim

2

In [24]:
MATRIX.size()

torch.Size([2, 3])

In [34]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [35]:
TENSOR.ndim

3

In [36]:
TENSOR.shape

torch.Size([1, 4, 3])

In [40]:
### RANDOM TENSORS

In [41]:
random_tensor = torch.rand(size = (3,4,5))

In [44]:
random_tensor, random_tensor.dtype

(tensor([[[0.4833, 0.7438, 0.0143, 0.4032, 0.8888],
          [0.3329, 0.4983, 0.9962, 0.0402, 0.6374],
          [0.2999, 0.2487, 0.4050, 0.7565, 0.5869],
          [0.2179, 0.7667, 0.2188, 0.9059, 0.8967]],
 
         [[0.7570, 0.1246, 0.6215, 0.0459, 0.2112],
          [0.4235, 0.2597, 0.7324, 0.3333, 0.4360],
          [0.3234, 0.4958, 0.4610, 0.7457, 0.9387],
          [0.0096, 0.5487, 0.6974, 0.8732, 0.4320]],
 
         [[0.1462, 0.8602, 0.9570, 0.3947, 0.5238],
          [0.3494, 0.8426, 0.8719, 0.1199, 0.9349],
          [0.2922, 0.1753, 0.3550, 0.3713, 0.9702],
          [0.1367, 0.1650, 0.2790, 0.6904, 0.7639]]]),
 torch.float32)

In [45]:
random_image_size_tensor = torch.rand(size=(224,224,3))

In [46]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [47]:
### Zero and One Tensors

In [49]:
zeros = torch.zeros(size=(2,3))
zeros, zeros.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32)

In [50]:
ones = torch.ones(size=(2,3))
ones, ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

In [51]:
### Range in tensors

In [52]:
to_ten = torch.arange(0,10,1)

In [53]:
to_ten, to_ten.dtype, to_ten.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64, torch.Size([10]))

In [54]:
### zero tensors like another tensor

In [56]:
ten_zeros = torch.zeros_like(input=to_ten)
ten_zeros, ten_zeros.shape, ten_zeros.dtype

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.Size([10]), torch.int64)

In [57]:
ten_zeros.device

device(type='cpu')

In [58]:
### Tensor Operations

In [62]:
# ADDITION, MULTIPLICATION, SUBTRACTION, DIVISION

In [61]:
# addition of a scalar to a tensor
vector + 10

tensor([11, 12, 13, 14])

In [64]:
# * for element-wise multiplication
vector * 10

tensor([10, 20, 30, 40])

In [65]:
# torch.matmul is significantly faster than looping
# torch.matmul for matrix multiplication
torch.matmul(vector,vector)

tensor(30)